#!/bin/bash

set -e

. script/bootstrap

go version
ls -l .git

echo "Verifying code is formatted via 'gofmt -s -w  go/'"
gofmt -s -w  go/
git diff # --exit-code --quiet

echo "Building"
script/build

cd .gopath/src/github.com/github/ccql

echo "Running unit tests"
go test ./go/...
